version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: src\BackEnd\Dockerfile
    depends_on:
    - db

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: src\FrontEnd\Dockerfile
    links:
          - backend

  db:
    image: "microsoft/mssql-server-windows-developer"
    environment:
      SA_PASSWORD: "ConferencePlanner1234$$"
      ACCEPT_EULA: "Y"